.apex/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Decommissioned</fullName>
                </value>
                <value>
                    <fullName>Boo</fullName>
                </value>
                <value>
                    <fullName>random</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Clothes</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/OrderItemTriggerTest.cls
@isTest
private class OrderItemTriggerTest {

	@isTest
	static void testBeforeInsert() {
		Product__c testProduct = new Product__c(
				Name = 'Test Product',
				Price__c = 100,
				Family__c = 'New',
				Type__c = 'Electronics'
		);
		insert testProduct;

		Order__c testOrder = new Order__c(
				Name = 'Test Order'
		);
		insert testOrder;

		OrderItem__c orderItem = new OrderItem__c(
				OrderId__c = testOrder.Id,
				ProductId__c = testProduct.Id,
				Quantity__c = 2
		);

		Test.startTest();
		insert orderItem;
		Test.stopTest();

		OrderItem__c insertedItem = [SELECT Price__c FROM OrderItem__c WHERE Id = :orderItem.Id];
		System.assertEquals(testProduct.Price__c, insertedItem.Price__c, 'Price should match the product price');
	}

	@isTest
	static void testBeforeUpdate() {
		Product__c testProduct = new Product__c(
				Name = 'Test Product',
				Price__c = 100,
				Family__c = 'New',
				Type__c = 'Electronics'
		);
		insert testProduct;

		Order__c testOrder = new Order__c(
				Name = 'Test Order'
		);
		insert testOrder;

		OrderItem__c orderItem = new OrderItem__c(
				OrderId__c = testOrder.Id,
				ProductId__c = testProduct.Id,
				Quantity__c = 2
		);
		insert orderItem;

		orderItem.Quantity__c = 3;
		Test.startTest();
		update orderItem;
		Test.stopTest();

		OrderItem__c updatedItem = [SELECT Price__c, Quantity__c FROM OrderItem__c WHERE Id = :orderItem.Id];
		System.assertEquals(testProduct.Price__c, updatedItem.Price__c, 'Price should remain unchanged');
		System.assertEquals(3, updatedItem.Quantity__c, 'Quantity should be updated');
	}

	@isTest
	static void testAfterInsert() {
		Product__c testProduct = new Product__c(
				Name = 'Test Product',
				Price__c = 100,
				Family__c = 'New',
				Type__c = 'Electronics'
		);
		insert testProduct;

		Order__c testOrder = new Order__c(
				Name = 'Test Order'
		);
		insert testOrder;

		OrderItem__c orderItem = new OrderItem__c(
				OrderId__c = testOrder.Id,
				ProductId__c = testProduct.Id,
				Quantity__c = 2
		);

		Test.startTest();
		insert orderItem;
		Test.stopTest();

		Order__c updatedOrder = [SELECT TotalProductCount__c, TotalPrice__c FROM Order__c WHERE Id = :testOrder.Id];
		System.assertEquals(2, updatedOrder.TotalProductCount__c, 'Total product count should be 2');
		System.assertEquals(200, updatedOrder.TotalPrice__c, 'Total price should be 200');
	}

	@isTest
	static void testAfterUpdate() {
		Product__c testProduct = new Product__c(
				Name = 'Test Product',
				Price__c = 100,
				Family__c = 'New',
				Type__c = 'Electronics'
		);
		insert testProduct;

		Order__c testOrder = new Order__c(
				Name = 'Test Order'
		);
		insert testOrder;

		OrderItem__c orderItem = new OrderItem__c(
				OrderId__c = testOrder.Id,
				ProductId__c = testProduct.Id,
				Quantity__c = 2
		);
		insert orderItem;

		orderItem.Quantity__c = 3;
		Test.startTest();
		update orderItem;
		Test.stopTest();

		Order__c updatedOrder = [SELECT TotalProductCount__c, TotalPrice__c FROM Order__c WHERE Id = :testOrder.Id];
		System.assertEquals(3, updatedOrder.TotalProductCount__c, 'Total product count should be 3');
		System.assertEquals(300, updatedOrder.TotalPrice__c, 'Total price should be 300');
	}

//	@isTest
//	static void testAfterDelete() {
//		Product__c testProduct = new Product__c(
//				Name = 'Test Product',
//				Price__c = 100,
//				Family__c = 'New',
//				Type__c = 'Electronics'
//		);
//		insert testProduct;
//
//		Order__c testOrder = new Order__c(
//				Name = 'Test Order'
//		);
//		insert testOrder;
//
//		OrderItem__c orderItem = new OrderItem__c(
//				OrderId__c = testOrder.Id,
//				ProductId__c = testProduct.Id,
//				Quantity__c = 2
//		);
//		insert orderItem;
//
//		Test.startTest();
//		delete orderItem;
//		Test.stopTest();
//
//		Order__c updatedOrder = [SELECT TotalProductCount__c, TotalPrice__c FROM Order__c WHERE Id = :testOrder.Id];
//		System.assertEquals(0, updatedOrder.TotalProductCount__c, 'Total product count should be 0');
//		System.assertEquals(0, updatedOrder.TotalPrice__c, 'Total price should be 0');
//	}
}