src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Decommissioned</fullName>
                </value>
                <value>
                    <fullName>Boo</fullName>
                </value>
                <value>
                    <fullName>random</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Clothes</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductController.cls
public with sharing class ProductController {
	@AuraEnabled(cacheable=true)
	public static List<Product2> getFilteredProducts(String family, String type) {
		String query = 'SELECT Id, Name, Family__c, Type__c FROM Product__c WHERE Family__c = :family AND Type__c = :type';

		if (family == null) {
			query = query.replace('Family__c = :family AND ', '');
		}
		if (type == null) {
			query = query.replace('Type__c = :type', '');
		}

		return Database.query(query);
	}
}